// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TallerMec.App.Persistencia.AppRepositorio;

#nullable disable

namespace TallerMec.App.Persistencia.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20220925055145_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TallerMec.App.Dominio.Entidades.Mecanico", b =>
                {
                    b.Property<string>("mecanicoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("fechaNacimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nivelEstudio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("revisionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehiculoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mecanicoId");

                    b.ToTable("Mecanics");
                });

            modelBuilder.Entity("TallerMec.App.Dominio.Entidades.Propietario", b =>
                {
                    b.Property<string>("propietarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("contrasenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaNacimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("revisionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehiculoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("propietarioId");

                    b.ToTable("Propietarios");
                });

            modelBuilder.Entity("TallerMec.App.Dominio.Entidades.Revision", b =>
                {
                    b.Property<string>("revisionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("fechaRev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mecanicoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehiculoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("revisionId");

                    b.ToTable("Revisions");
                });

            modelBuilder.Entity("TallerMec.App.Dominio.Entidades.Vehiculo", b =>
                {
                    b.Property<string>("vehiculoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("accesorios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("capacidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cilindraje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mecanicoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("revisionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vehiculoId");

                    b.ToTable("vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
